### ISSUE TITLE
Implementar cadastro de Colaboradores

### ISSUE THREAD

**Issue by felipemfp** [Projeto-SIAC/siac-old#18]
A ideia é abstrair de **Configurações** para **Simulado/Dados Gerais**.

**Comment by chicobentojr** [comment]
- [x] Corrigir exclusão de Colaborador. 

> _o colaborador some da lista principal, mas seus dados permanecem no banco de dados_

**Comment by chicobentojr** [comment]
- [x] Adicionar a opção de "Coordenador/Colaborador" de Simulado
