### ISSUE TITLE
Alterações de senha salvam a senha em texto puro

### ISSUE THREAD

**Issue by felipemfp** [Projeto-SIAC/siac-old#22]
Isso ocorre porque o registro de acessos não filtra os dados nem criptografa para salvar no banco de dados.

**Comment by chicobentojr** [comment]
Isto também ocorre no cadastro de qualquer categoria de usuário

**Comment by felipemfp** [comment]
Procurar uma biblioteca de criptografia baseada em chaves para encriptar e decriptar.

/cc @chicobentojr

**Comment by felipemfp** [comment]
Vou fechar por enquanto, porque não parecem dados sensitivos os que são salvos.
