### ISSUE TITLE
Migrar para ASP.NET Core ou modular em MVC Areas

### ISSUE THREAD

**Issue by felipemfp** [Projeto-SIAC/siac-old#26]
Qual a próxima etapa?

**Comment by chicobentojr** [comment]
@felipemfp Minha opinião: Migrar para ASP.NET Core

**Comment by felipemfp** [comment]
Concordo também.

Vai ser divertido :smile:

**Comment by felipemfp** [comment]
Já foi decidido.

**Comment by chicobentojr** [comment]
Vai ser divertido :smile:
