### ISSUE TITLE
Simplificar sistema de simulado

### ISSUE THREAD

**Issue by chicobentojr** [Projeto-SIAC/siac-old#32]
Verificar todo os arquivos do sistema para remover as funcionalidades que não serão mais utilizadas:
- [x] Tela de principal
- [x] Controllers
- [x] Views
- [x] Bundle
- [x] Corrigir rotas | issue #31 
- [x] Helpers
- [x] Models (partials e não utilizados)
- [x] Scripts
- [x] Sitemap
- [x] Projeto de testes
- [x] Hubs

**Comment by chicobentojr** [comment]
@felipemfp vai adicionando o que mais você lembrar

**Comment by felipemfp** [comment]
Adicionei **Hubs**, que já foi feito em f934278ffc2a33428aeebda9885e935704b48a49

**Comment by felipemfp** [comment]
@chicobentojr, chequei novamente e não encontrei mais nada. Fechar?

**Comment by chicobentojr** [comment]
@felipemfp acredito que sim
