### ISSUE TITLE
Verificar cadastros do Simulado

### ISSUE THREAD

**Issue by felipemfp** [Projeto-SIAC/siac-old#4]
Buscar por rotinas que necessitem de confirmação, verificar funcionamento e apontar novas necessidades.

**Checklist**
- [x] Dados do Simulado
- [x] Datas
- [x] Provas
- [x] Salas

**Comment by chicobentojr** [comment]
### Anotações

#### Cadastro de Simulado
- [x] Atualizar a **Nota de Uso**.

#### Detalhe de Simulado
- [x] A tag informativa está aparecendo **Inscrições Encerradas sem candidatos** mesmo quando o simulado não teve ao menos uma data de inscrição cadastrada.
- [x] Verificar todo o uso das tags informativas.

#### Provas do Simulado
- [x] Quando clico em _Editar_ o dia, ele duplica a página atual do sistema.
- [x] Não existe confirmação na hora de _Remover Prova_ de um dia.

**Comment by felipemfp** [comment]
Atualizar a **Nota de Uso** é a cargo do usuário. A rotina está feita.
